/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemamanager.GUI;

import cinemamanager.BUS.PaymentBUS;
import cinemamanager.DTO.Payment;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FTEL
 */
public class CancelPayment extends javax.swing.JFrame {

    String theater = "";
    int idSelect =-1;
    String Chair = "";
    int showtimeID = 0;
    /**
     * Creates new form CancelPayment
     */
    public CancelPayment(String theater) {
        initComponents();
        this.theater = theater;
        try {
            getData();
        } catch (SQLException ex) {
            Logger.getLogger(CancelPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CancelPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollbarMovie = new javax.swing.JScrollPane();
        tablePayment = new javax.swing.JTable();
        btnHuyVe = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollbarMovie.setBorder(null);

        tablePayment.setBackground(new java.awt.Color(239, 249, 249));
        tablePayment.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tablePayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PaymentID", "Tên người mua", "Tên Phim", "Ngày mua", "Tổng tiền", "Thực trả", "Loại thanh toán", "Ghế đặt", "ShowTimeID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollbarMovie.setViewportView(tablePayment);

        btnHuyVe.setBackground(new java.awt.Color(255, 255, 255));
        btnHuyVe.setText("Hủy vé");
        btnHuyVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyVeActionPerformed(evt);
            }
        });

        btnBack.setText("Thoát");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollbarMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHuyVe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scrollbarMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuyVe)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyVeActionPerformed
        if(idSelect != -1){
            if(PaymentBUS.cancelPayment(idSelect, Chair,showtimeID) ==1)
            {
                JOptionPane.showMessageDialog(null, "Hủy vé thành công.");  
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Hủy vé không thành công.");  
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnHuyVeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHuyVe;
    private javax.swing.JScrollPane scrollbarMovie;
    private javax.swing.JTable tablePayment;
    // End of variables declaration//GEN-END:variables

    private void getData() throws SQLException, ParseException {
        ArrayList<Payment> lst = PaymentBUS.getPayment(theater);
        DefaultTableModel modelMovies = (DefaultTableModel) tablePayment.getModel();
        modelMovies.setRowCount(0);
        for (int i = 0 ;i < lst.size();i++) {
                Object[] row = new Object[9];
                row[0] = lst.get(i).getID();
                row[1] = lst.get(i).getUserName();
                row[2] = lst.get(i).getMovie();
                row[3] = lst.get(i).getDatePay();
                row[4] = lst.get(i).getTotal();
                row[5] = lst.get(i).getAmout();
                row[6] = lst.get(i).getPaidType();
                row[7] = lst.get(i).getChair();
                row[8] = lst.get(i).getShowtimeID();
                modelMovies.addRow(row);
            }
        
        tablePayment.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
          int a = event.getFirstIndex();
          if(a >= 0 && a < tablePayment.getRowCount())
                {
                    idSelect = Integer.parseInt(tablePayment.getValueAt(tablePayment.getSelectedRow(), 0).toString());
                    Chair = tablePayment.getValueAt(tablePayment.getSelectedRow(), 7).toString();
                    showtimeID = Integer.parseInt(tablePayment.getValueAt(tablePayment.getSelectedRow(), 8).toString());
                }
               
            
        }});
        
    }
}
