/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemamanager.GUI;

import cinemamanager.BUS.RoomBUS;
import cinemamanager.BUS.TheaterBUS;
import cinemamanager.DTO.Chair;
import cinemamanager.DTO.Room;
import cinemamanager.DTO.Theater;
import java.awt.Color;
import java.awt.Component;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;

/**
 *
 * @author Totoro
 */
public class ChairManager extends javax.swing.JFrame {
    
    /**
     * Creates new form ChairManager
     */
    public ChairManager() {
        this.btnClicked = new HashMap<String, Integer>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbbRap = new javax.swing.JComboBox<>();
        cbbPhongChieu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        btnBackCinema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        MainPanel.setBackground(new java.awt.Color(255, 204, 204));

        jButton16.setBackground(new java.awt.Color(255, 102, 102));
        jButton16.setText("B0");

        jButton21.setBackground(new java.awt.Color(255, 102, 102));
        jButton21.setText("G0");

        jButton19.setBackground(new java.awt.Color(255, 102, 102));
        jButton19.setText("E0");

        jButton20.setBackground(new java.awt.Color(255, 102, 102));
        jButton20.setText("F0");

        jButton15.setBackground(new java.awt.Color(255, 102, 102));
        jButton15.setText("A0");

        jButton18.setBackground(new java.awt.Color(255, 102, 102));
        jButton18.setText("D0");

        jButton17.setBackground(new java.awt.Color(255, 102, 102));
        jButton17.setText("C0");

        jButton22.setBackground(new java.awt.Color(255, 102, 102));
        jButton22.setText("A1");

        jButton23.setBackground(new java.awt.Color(255, 102, 102));
        jButton23.setText("B1");

        jButton24.setBackground(new java.awt.Color(255, 102, 102));
        jButton24.setText("C1");

        jButton25.setBackground(new java.awt.Color(255, 102, 102));
        jButton25.setText("D1");

        jButton26.setBackground(new java.awt.Color(255, 102, 102));
        jButton26.setText("E1");

        jButton27.setBackground(new java.awt.Color(255, 102, 102));
        jButton27.setText("F1");

        jButton28.setBackground(new java.awt.Color(255, 102, 102));
        jButton28.setText("G1");

        jButton29.setBackground(new java.awt.Color(255, 102, 102));
        jButton29.setText("A2");

        jButton30.setBackground(new java.awt.Color(255, 102, 102));
        jButton30.setText("B2");

        jButton31.setBackground(new java.awt.Color(255, 102, 102));
        jButton31.setText("C2");

        jButton32.setBackground(new java.awt.Color(255, 102, 102));
        jButton32.setText("D2");

        jButton33.setBackground(new java.awt.Color(255, 102, 102));
        jButton33.setText("E2");

        jButton34.setBackground(new java.awt.Color(255, 102, 102));
        jButton34.setText("F2");

        jButton35.setBackground(new java.awt.Color(255, 102, 102));
        jButton35.setText("G2");

        jButton36.setBackground(new java.awt.Color(255, 102, 102));
        jButton36.setText("A3");

        jButton37.setBackground(new java.awt.Color(255, 102, 102));
        jButton37.setText("B3");

        jButton38.setBackground(new java.awt.Color(255, 102, 102));
        jButton38.setText("C3");

        jButton39.setBackground(new java.awt.Color(255, 102, 102));
        jButton39.setText("D3");

        jButton40.setBackground(new java.awt.Color(255, 102, 102));
        jButton40.setText("E3");

        jButton41.setBackground(new java.awt.Color(255, 102, 102));
        jButton41.setText("F3");

        jButton42.setBackground(new java.awt.Color(255, 102, 102));
        jButton42.setText("G3");

        jButton43.setBackground(new java.awt.Color(255, 102, 102));
        jButton43.setText("A4");

        jButton44.setBackground(new java.awt.Color(255, 102, 102));
        jButton44.setText("B4");

        jButton45.setBackground(new java.awt.Color(255, 102, 102));
        jButton45.setText("C4");

        jButton46.setBackground(new java.awt.Color(255, 102, 102));
        jButton46.setText("D4");

        jButton47.setBackground(new java.awt.Color(255, 102, 102));
        jButton47.setText("E4");

        jButton48.setBackground(new java.awt.Color(255, 102, 102));
        jButton48.setText("F4");

        jButton49.setBackground(new java.awt.Color(255, 102, 102));
        jButton49.setText("G4");

        jButton50.setBackground(new java.awt.Color(255, 102, 102));
        jButton50.setText("A5");

        jButton51.setBackground(new java.awt.Color(255, 102, 102));
        jButton51.setText("B5");

        jButton52.setBackground(new java.awt.Color(255, 102, 102));
        jButton52.setText("C5");

        jButton53.setBackground(new java.awt.Color(255, 102, 102));
        jButton53.setText("D5");

        jButton54.setBackground(new java.awt.Color(255, 102, 102));
        jButton54.setText("E5");

        jButton55.setBackground(new java.awt.Color(255, 102, 102));
        jButton55.setText("F5");

        jButton56.setBackground(new java.awt.Color(255, 102, 102));
        jButton56.setText("G5");

        jButton57.setBackground(new java.awt.Color(255, 102, 102));
        jButton57.setText("A6");

        jButton58.setBackground(new java.awt.Color(255, 102, 102));
        jButton58.setText("B6");

        jButton59.setBackground(new java.awt.Color(255, 102, 102));
        jButton59.setText("C6");

        jButton60.setBackground(new java.awt.Color(255, 102, 102));
        jButton60.setText("D6");

        jButton61.setBackground(new java.awt.Color(255, 102, 102));
        jButton61.setText("E6");

        jButton62.setBackground(new java.awt.Color(255, 102, 102));
        jButton62.setText("F6");

        jButton63.setBackground(new java.awt.Color(255, 102, 102));
        jButton63.setText("G6");

        jButton64.setBackground(new java.awt.Color(255, 102, 102));
        jButton64.setText("A7");

        jButton65.setBackground(new java.awt.Color(255, 102, 102));
        jButton65.setText("B7");

        jButton66.setBackground(new java.awt.Color(255, 102, 102));
        jButton66.setText("C7");

        jButton67.setBackground(new java.awt.Color(255, 102, 102));
        jButton67.setText("D7");

        jButton68.setBackground(new java.awt.Color(255, 102, 102));
        jButton68.setText("E7");

        jButton69.setBackground(new java.awt.Color(255, 102, 102));
        jButton69.setText("F7");

        jButton70.setBackground(new java.awt.Color(255, 102, 102));
        jButton70.setText("G7");

        jButton71.setBackground(new java.awt.Color(255, 102, 102));
        jButton71.setText("A8");

        jButton72.setBackground(new java.awt.Color(255, 102, 102));
        jButton72.setText("B8");

        jButton73.setBackground(new java.awt.Color(255, 102, 102));
        jButton73.setText("C8");

        jButton74.setBackground(new java.awt.Color(255, 102, 102));
        jButton74.setText("D8");

        jButton75.setBackground(new java.awt.Color(255, 102, 102));
        jButton75.setText("E8");

        jButton76.setBackground(new java.awt.Color(255, 102, 102));
        jButton76.setText("F8");

        jButton77.setBackground(new java.awt.Color(255, 102, 102));
        jButton77.setText("G8");

        jButton78.setBackground(new java.awt.Color(255, 102, 102));
        jButton78.setText("A9");

        jButton79.setBackground(new java.awt.Color(255, 102, 102));
        jButton79.setText("B9");

        jButton80.setBackground(new java.awt.Color(255, 102, 102));
        jButton80.setText("C9");

        jButton81.setBackground(new java.awt.Color(255, 102, 102));
        jButton81.setText("D9");

        jButton82.setBackground(new java.awt.Color(255, 102, 102));
        jButton82.setText("E9");

        jButton83.setBackground(new java.awt.Color(255, 102, 102));
        jButton83.setText("F9");

        jButton84.setBackground(new java.awt.Color(255, 102, 102));
        jButton84.setText("G9");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton57, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton58, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton59, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton62, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton66, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton67, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton68, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton69, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton70, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton71, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton73, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton74, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton75, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton76, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton77, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton78, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton79, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton80, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton81, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton82, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton83, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton84, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jButton78)
                        .addGap(26, 26, 26)
                        .addComponent(jButton79)
                        .addGap(26, 26, 26)
                        .addComponent(jButton80)
                        .addGap(30, 30, 30)
                        .addComponent(jButton81)
                        .addGap(35, 35, 35)
                        .addComponent(jButton82)
                        .addGap(30, 30, 30)
                        .addComponent(jButton83)
                        .addGap(30, 30, 30)
                        .addComponent(jButton84))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jButton71)
                        .addGap(26, 26, 26)
                        .addComponent(jButton72)
                        .addGap(26, 26, 26)
                        .addComponent(jButton73)
                        .addGap(30, 30, 30)
                        .addComponent(jButton74)
                        .addGap(35, 35, 35)
                        .addComponent(jButton75)
                        .addGap(30, 30, 30)
                        .addComponent(jButton76)
                        .addGap(30, 30, 30)
                        .addComponent(jButton77))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jButton64)
                        .addGap(26, 26, 26)
                        .addComponent(jButton65)
                        .addGap(26, 26, 26)
                        .addComponent(jButton66)
                        .addGap(30, 30, 30)
                        .addComponent(jButton67)
                        .addGap(35, 35, 35)
                        .addComponent(jButton68)
                        .addGap(30, 30, 30)
                        .addComponent(jButton69)
                        .addGap(30, 30, 30)
                        .addComponent(jButton70))
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addComponent(jButton57)
                            .addGap(26, 26, 26)
                            .addComponent(jButton58)
                            .addGap(26, 26, 26)
                            .addComponent(jButton59)
                            .addGap(30, 30, 30)
                            .addComponent(jButton60)
                            .addGap(35, 35, 35)
                            .addComponent(jButton61)
                            .addGap(30, 30, 30)
                            .addComponent(jButton62)
                            .addGap(30, 30, 30)
                            .addComponent(jButton63))
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addComponent(jButton50)
                            .addGap(26, 26, 26)
                            .addComponent(jButton51)
                            .addGap(26, 26, 26)
                            .addComponent(jButton52)
                            .addGap(30, 30, 30)
                            .addComponent(jButton53)
                            .addGap(35, 35, 35)
                            .addComponent(jButton54)
                            .addGap(30, 30, 30)
                            .addComponent(jButton55)
                            .addGap(30, 30, 30)
                            .addComponent(jButton56))
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(jButton43)
                                .addGap(26, 26, 26)
                                .addComponent(jButton44)
                                .addGap(26, 26, 26)
                                .addComponent(jButton45)
                                .addGap(30, 30, 30)
                                .addComponent(jButton46)
                                .addGap(35, 35, 35)
                                .addComponent(jButton47)
                                .addGap(30, 30, 30)
                                .addComponent(jButton48)
                                .addGap(30, 30, 30)
                                .addComponent(jButton49))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(jButton36)
                                .addGap(26, 26, 26)
                                .addComponent(jButton37)
                                .addGap(26, 26, 26)
                                .addComponent(jButton38)
                                .addGap(30, 30, 30)
                                .addComponent(jButton39)
                                .addGap(35, 35, 35)
                                .addComponent(jButton40)
                                .addGap(30, 30, 30)
                                .addComponent(jButton41)
                                .addGap(30, 30, 30)
                                .addComponent(jButton42))
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(MainPanelLayout.createSequentialGroup()
                                    .addComponent(jButton29)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButton30)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButton31)
                                    .addGap(30, 30, 30)
                                    .addComponent(jButton32)
                                    .addGap(35, 35, 35)
                                    .addComponent(jButton33)
                                    .addGap(30, 30, 30)
                                    .addComponent(jButton34)
                                    .addGap(30, 30, 30)
                                    .addComponent(jButton35))
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addComponent(jButton22)
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton23)
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton24)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton25)
                                        .addGap(35, 35, 35)
                                        .addComponent(jButton26)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton27)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton28))
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addComponent(jButton15)
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton16)
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton17)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton18)
                                        .addGap(35, 35, 35)
                                        .addComponent(jButton19)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton20)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton21)))))))
                .addGap(21, 21, 21))
        );

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("A");

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("B");

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setText("C");

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setText("D");

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setText("E");

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setText("F");

        jButton7.setBackground(new java.awt.Color(255, 102, 102));
        jButton7.setText("G");

        jButton8.setBackground(new java.awt.Color(255, 102, 102));
        jButton8.setText("A");

        jButton9.setBackground(new java.awt.Color(255, 102, 102));
        jButton9.setText("B");

        jButton10.setBackground(new java.awt.Color(255, 102, 102));
        jButton10.setText("C");

        jButton11.setBackground(new java.awt.Color(255, 102, 102));
        jButton11.setText("D");

        jButton12.setBackground(new java.awt.Color(255, 102, 102));
        jButton12.setText("E");

        jButton13.setBackground(new java.awt.Color(255, 102, 102));
        jButton13.setText("F");

        jButton14.setBackground(new java.awt.Color(255, 102, 102));
        jButton14.setText("G");

        jButton90.setBackground(new java.awt.Color(255, 102, 102));
        jButton90.setText("5");

        jButton88.setBackground(new java.awt.Color(255, 102, 102));
        jButton88.setText("3");

        jButton94.setBackground(new java.awt.Color(255, 102, 102));
        jButton94.setText("9");

        jButton86.setBackground(new java.awt.Color(255, 102, 102));
        jButton86.setText("1");

        jButton87.setBackground(new java.awt.Color(255, 102, 102));
        jButton87.setText("2");

        jButton91.setBackground(new java.awt.Color(255, 102, 102));
        jButton91.setText("6");

        jButton92.setBackground(new java.awt.Color(255, 102, 102));
        jButton92.setText("7");

        jButton89.setBackground(new java.awt.Color(255, 102, 102));
        jButton89.setText("4");

        jButton85.setBackground(new java.awt.Color(255, 102, 102));
        jButton85.setText("0");

        jButton93.setBackground(new java.awt.Color(255, 102, 102));
        jButton93.setText("8");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCREEN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setText("Rạp phim:");

        jLabel3.setText("Phòng chiếu:");

        jButton95.setBackground(new java.awt.Color(0, 102, 102));
        jButton95.setForeground(new java.awt.Color(255, 255, 255));
        jButton95.setText("Lưu lại");
        jButton95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton95ActionPerformed(evt);
            }
        });

        jButton96.setBackground(new java.awt.Color(255, 255, 255));
        jButton96.setText("Đang sử dụng");

        jButton97.setBackground(java.awt.Color.red);
        jButton97.setText("Chưa có ghế");

        jButton98.setBackground(java.awt.Color.green);
        jButton98.setText("Ghế muốn xóa");

        jButton99.setBackground(new java.awt.Color(255, 255, 0));
        jButton99.setText("Ghế sẽ thêm");

        btnBackCinema.setText("Go to Cinema Manager");
        btnBackCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCinemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton96, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton97, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton99, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton98, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton95, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBackCinema))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbRap, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbPhongChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton85, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton86, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton87, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton88, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton89, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton90, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton91, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton92, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton93, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton94, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbRap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPhongChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3)
                                .addGap(30, 30, 30)
                                .addComponent(jButton4)
                                .addGap(35, 35, 35)
                                .addComponent(jButton5)
                                .addGap(30, 30, 30)
                                .addComponent(jButton6)
                                .addGap(30, 30, 30)
                                .addComponent(jButton7)
                                .addGap(21, 21, 21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(26, 26, 26)
                        .addComponent(jButton9)
                        .addGap(26, 26, 26)
                        .addComponent(jButton10)
                        .addGap(30, 30, 30)
                        .addComponent(jButton11)
                        .addGap(35, 35, 35)
                        .addComponent(jButton12)
                        .addGap(30, 30, 30)
                        .addComponent(jButton13)
                        .addGap(30, 30, 30)
                        .addComponent(jButton14)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton94)
                    .addComponent(jButton93)
                    .addComponent(jButton92)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton91)
                        .addComponent(jButton90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton89)
                            .addComponent(jButton88)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton86)
                                    .addComponent(jButton85))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton96)
                    .addComponent(jButton97)
                    .addComponent(jButton98)
                    .addComponent(jButton95)
                    .addComponent(jButton99)
                    .addComponent(btnBackCinema))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            getTheaters();
            showTheatersToCombobox(theaters);
        } catch (SQLException ex) {
            Logger.getLogger(ChairManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton95ActionPerformed
        save();
    }//GEN-LAST:event_jButton95ActionPerformed

    private void btnBackCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCinemaActionPerformed
        new CinemaMagager().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackCinemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChairManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChairManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChairManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChairManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChairManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnBackCinema;
    private javax.swing.JComboBox<String> cbbPhongChieu;
    private javax.swing.JComboBox<String> cbbRap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Theater> theaters = new ArrayList<>();
    private ArrayList<Room> rooms = new ArrayList<>();
    private ArrayList<Chair> chairs = new ArrayList<>();

    Vector maRap = new Vector();
    Vector tenRap = new Vector();

    Vector maPhong = new Vector();
    Vector tenPhong = new Vector();

    Vector maGhe = new Vector();
    Vector tenGhe = new Vector();

    Map<String, Integer> btnClicked;
    Map<String, ArrayList<Integer>> btnLocation = null;

    public void getTheaters() throws SQLException {
        TheaterBUS theaterBUS = new TheaterBUS();
        theaters = theaterBUS.getTheaters();
    }

    public void getRooms(int theaterID) throws SQLException {
        RoomBUS roomBUS = new RoomBUS();
        rooms = roomBUS.getRooms(theaterID);
    }

    public void getChairs(int roomID) throws SQLException {
        RoomBUS roomBUS = new RoomBUS();
        chairs = roomBUS.getChairs(roomID);
    }

    public void changeStatusOfButton(String name, int status) {
        if (btnClicked.containsKey(name)) {
            btnClicked.replace(name, status);
        } else {
            btnClicked.put(name, status);
        }
    }
    
    public void changeLocationOfButton(String name, int[] status) {
        if (!btnLocation.containsKey(name)) {
            ArrayList<Integer> arr = new ArrayList();
            arr.add(new Integer(status[0])); // x
            arr.add(new Integer(status[1])); // y
            btnLocation.put(name, arr);
        }
    }

    private void showTheatersToCombobox(ArrayList<Theater> theaters) {
        for (int i = 0; i < theaters.size(); i++) {
            maRap.add(theaters.get(i).getId());
            tenRap.add(theaters.get(i).getName());
        }
        cbbRap.setModel(new DefaultComboBoxModel<>(tenRap));
        cbbRap.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    cbbPhongChieu.removeAll();
                    tenPhong.clear();
                    maPhong.clear();
                    getRooms(Integer.parseInt(maRap.get(cbbRap.getSelectedIndex()).toString()));
                    for (int i = 0; i < rooms.size(); i++) {
                        maPhong.add(rooms.get(i).getId());
                        tenPhong.add(rooms.get(i).getRoomName());
                    }
                    cbbPhongChieu.setModel(new DefaultComboBoxModel<>(tenPhong));

                } catch (SQLException ex) {
                    Logger.getLogger(RoomManager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        cbbPhongChieu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    changallColor();
                    chairs.clear();
                    getChairs(Integer.parseInt(maPhong.get(cbbPhongChieu.getSelectedIndex()).toString()));

                    System.out.println(chairs.size());
                    int n = chairs.size();
                    // normal 1
                    // green 2
                    // yellow 3
                    
                    if(btnLocation == null){
                        btnLocation = new HashMap<String, ArrayList<Integer>>();
                    }
                    
                    for (int i = 0; i < n; i++) {
                        for (Component btn : MainPanel.getComponents()) {
                            JButton jbtn = (JButton) btn;
                            //System.out.println( jbtn.getText());
                            //System.out.println(chairs.get(i).getStatus());
                            if (chairs.get(i).getNameChair().equals(jbtn.getText()) && chairs.get(i).getStatus() == 1) {
                                // reset
                                jbtn.setBackground(Color.red);
                                if (jbtn.getActionListeners().length > 0) {
                                    int k = jbtn.getActionListeners().length;
                                    for(int j = 0; j < k; j++){
                                        jbtn.removeActionListener(jbtn.getActionListeners()[j]);
                                    }
                                }
                                
                                jbtn.setBackground(Color.white);
                                changeLocationOfButton(jbtn.getText(), new int[]{jbtn.getX(), jbtn.getY()});
                                //jbtn.add(chairs.get(i));
                                jbtn.addActionListener(new ActionListener() {
                                    @Override
                                    public void actionPerformed(ActionEvent e) {
                                        if (jbtn.getBackground().equals(Color.green)) { // chưa có
                                            jbtn.setBackground(Color.white);
                                            changeStatusOfButton(jbtn.getText(), 1);
                                        } else { // đã có
                                            jbtn.setBackground(Color.green); 
                                            changeStatusOfButton(jbtn.getText(), 2);
                                        }
                                    }
                                });
                                break;
                            }

                        }
                    }

                    for (Component btn : MainPanel.getComponents()) {
                        JButton jbtn = (JButton) btn;
                        boolean isThis = false;
                        //System.out.println( jbtn.getText());
                        for (int i = 0; i < n; i++) {
                            if (chairs.get(i).getNameChair().equals(jbtn.getText())) {
                                isThis = true;
                            }
                        }

                        if (isThis == false) {
                            // reset
                            changeLocationOfButton(jbtn.getText(), new int[]{jbtn.getX(), jbtn.getY()});
                                jbtn.setBackground(Color.red);
                                if (jbtn.getActionListeners().length > 0) {
                                    int k = jbtn.getActionListeners().length;
                                    for(int j = 0; j < k; j++){
                                        jbtn.removeActionListener(jbtn.getActionListeners()[j]);
                                    }
                                }
                            jbtn.addActionListener(new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e) {
                                    if (jbtn.getBackground().equals(Color.yellow)) {
                                        jbtn.setBackground(Color.red);
                                        changeStatusOfButton(jbtn.getText(), 1);
                                    } else {
                                        jbtn.setBackground(Color.yellow);
                                        changeStatusOfButton(jbtn.getText(), 3);
                                    }
                                }
                            });
                        }
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(ChairManager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void save() {
        ArrayList names = new ArrayList(btnClicked.keySet());
        int n = names.size();
        int roomID = Integer.parseInt(maPhong.get(cbbPhongChieu.getSelectedIndex()).toString());
        System.out.println(roomID);
        int idx = cbbPhongChieu.getSelectedIndex();
        for (int i = 0; i < n; i++) {
            if (btnClicked.get(names.get(i)) == 2) {
                String chairName = names.get(i).toString();
                if (deleteChair(chairName, roomID) > 0) {
                    //System.out.println("delete done !");
                }

            }
            if (btnClicked.get(names.get(i)) == 3) {
                String chairName = names.get(i).toString();
                
                int x = btnLocation.get(names.get(i)).get(0);
                int y = btnLocation.get(names.get(i)).get(1);
                Chair chair = new Chair(0, chairName, roomID, 1, x, y, 1);
                insertChair(chair);
            }
        }
        btnClicked.clear();
        cbbPhongChieu.setSelectedIndex(idx);
    }

    private int deleteChair(String chairName, int roomID) {
        RoomBUS roomBUS = new RoomBUS();
        return roomBUS.deleteChair(chairName, roomID);
    }

    public void changallColor() {
//        for (Component btn : MainPanel.getComponents()) {
//            JButton jbtn = (JButton) btn;
//            
//
//        }
    }

    private int insertChair(Chair chair) {
        RoomBUS roomBUS = new RoomBUS();
        return roomBUS.insertChair(chair);
    }
}
