/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemamanager.GUI;

import java.awt.Color;

/**
 *
 * @author Totoro
 */
public class CinemaMagager extends javax.swing.JFrame {

    /**
     * Creates new form CinemaMagager
     */
    public CinemaMagager() {
        initComponents();
        btnMovieManager.setBackground(new Color(0,102,102));
        btnChairManager.setBackground(new Color(0,102,102));
        btnRoomManager.setBackground(new Color(0,102,102));
        btnTheaterManager.setBackground(new Color(0,102,102));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTheaterManager = new javax.swing.JButton();
        btnMovieManager = new javax.swing.JButton();
        btnRoomManager = new javax.swing.JButton();
        btnChairManager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/logo.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnTheaterManager.setBackground(new java.awt.Color(0, 102, 102));
        btnTheaterManager.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnTheaterManager.setForeground(new java.awt.Color(255, 255, 255));
        btnTheaterManager.setText("Theater Manager");
        btnTheaterManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheaterManagerActionPerformed(evt);
            }
        });

        btnMovieManager.setBackground(new java.awt.Color(0, 102, 102));
        btnMovieManager.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnMovieManager.setForeground(new java.awt.Color(255, 255, 255));
        btnMovieManager.setText("Movie Manager");
        btnMovieManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieManagerActionPerformed(evt);
            }
        });

        btnRoomManager.setBackground(new java.awt.Color(0, 102, 102));
        btnRoomManager.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnRoomManager.setForeground(new java.awt.Color(255, 255, 255));
        btnRoomManager.setText("Room Manager");
        btnRoomManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomManagerActionPerformed(evt);
            }
        });

        btnChairManager.setBackground(new java.awt.Color(0, 102, 102));
        btnChairManager.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnChairManager.setForeground(new java.awt.Color(255, 255, 255));
        btnChairManager.setText("Chair Manager");
        btnChairManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChairManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMovieManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChairManager)
                .addGap(11, 11, 11)
                .addComponent(btnRoomManager, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTheaterManager)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTheaterManager, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMovieManager, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoomManager, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChairManager, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMovieManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieManagerActionPerformed
        new MovieManager().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMovieManagerActionPerformed

    private void btnChairManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChairManagerActionPerformed
        new ChairManager().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnChairManagerActionPerformed

    private void btnRoomManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomManagerActionPerformed
        new RoomManager().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnRoomManagerActionPerformed

    private void btnTheaterManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheaterManagerActionPerformed
        new TheaterManager().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnTheaterManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CinemaMagager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CinemaMagager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChairManager;
    private javax.swing.JButton btnMovieManager;
    private javax.swing.JButton btnRoomManager;
    private javax.swing.JButton btnTheaterManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
